### ISSUE TITLE
Support WOFF2

### ISSUE THREAD

**Issue by Skif-off** [danpla/wdx_fontinfo#1]
Is it possible to add?

**Comment by danpla** [comment]
Yes, I think it's possible, but this requires linking with the [brotli](https://github.com/google/brotli) library. The building process will be slightly more complicated since people will also need a C compiler in addition to FPC. On the other hand, it's possible to make WOFF2 support optional.

**Comment by Skif-off** [comment]
It's good, thanks!
Can you add something like `brotli.dll` or `brotlidec.dll` to release for Windows users? Or maybe this solution has license limitations?
Or maybe add web link to a page with ready-made DLL files? I did not find them.

For Linux/BSD users, it's easier, because brotli library exists in package lists of popular distributions, but with one nuance:
- Arch Linux:
```
usr/lib/libbrotlicommon.so
usr/lib/libbrotlicommon.so.1
usr/lib/libbrotlicommon.so.1.0.7
usr/lib/libbrotlidec.so
usr/lib/libbrotlidec.so.1
usr/lib/libbrotlidec.so.1.0.7
```
- but Debian/Ubuntu-based distributions (looks like greedies :)):
```
/usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1
/usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1.0.7
/usr/lib/x86_64-linux-gnu/libbrotlidec.so.1
/usr/lib/x86_64-linux-gnu/libbrotlidec.so.1.0.7
```

**Comment by Skif-off** [comment]
Works fine on Linux (Debian 9, Xubuntu 18.04), thanks!
But I can not build on Windows.

**Comment by danpla** [comment]
It's not complete yet. I'll add building instructions when it's ready.

**Comment by danpla** [comment]
Version 1.1.0 is available, you can find the binaries here: https://github.com/danpla/wdx_fontinfo/releases
